const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const clean=(v,max=200)=>typeof v==='string'?v.trim().slice(0,max):'';
const bookKeys=['title','subtitle','color','theme','frame','font','icon','titleSize','titleAlign','customBg','customAccent','customInk','coverPhoto','coverPhotoY','coverFilter','coverZoom','titleEffect','pageLayout','pagePhotoShape','pageFont','pageTextSize','layout','pageDate','pagePlace','pageNotes','pagePaper','pagePattern'];
function bookData(src){const b={};for(const k of bookKeys)if(src[k]!==undefined&&['string','number','boolean'].includes(typeof src[k]))b[k]=src[k];for(const key of ['color','theme','frame','font','icon','pageFont'])if(b[key]!==undefined&&(!Number.isInteger(b[key])||b[key]<0||b[key]>1000))fail(400,'デザインの値を確認してください');for(const key of ['customBg','customAccent','customInk'])if(b[key]&&!/^#[a-f0-9]{6}$/i.test(b[key]))fail(400,'色の値を確認してください');b.title=clean(b.title,48);if(!b.title)fail(400,'図鑑の名前を入力してください');if(b.coverPhoto&&(!/^data:image\/jpeg;base64,[A-Za-z0-9+/]+=*$/.test(b.coverPhoto)||b.coverPhoto.length>2000000))fail(400,'表紙写真を選び直してください');return b}
function entryData(src){const e={};for(const k of ['name','kanji','observed','imagined'])e[k]=clean(src[k],k==='name'?100:4000);if(!e.name)fail(400,'記録の名前を入力してください');return e}
async function body(req){if(Number(req.headers.get('content-length'))>8000000)fail(413,'写真が大きすぎます');const raw=await req.text();if(raw.length>8000000)fail(413,'写真が大きすぎます');try{return JSON.parse(raw)}catch{fail(400,'入力を確認してください')}}
function identity(req){const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');return id&&email?{id,email:email.toLowerCase()}:null}
async function access(env,id,user,owner=false){if(!user)fail(401,'ログインが必要です');const group=await env.DB.prepare('SELECT * FROM groups WHERE id = ?').bind(id).first();if(!group)fail(404,'図鑑が見つかりません');if(group.owner!==user.id){if(owner)fail(403,'作成者だけが操作できます');const member=await env.DB.prepare('SELECT role FROM members WHERE group_id = ? AND email = ?').bind(id,user.email).first();if(!member)fail(403,'この図鑑への招待が必要です')}return group}
async function savePhoto(env,gid,data){if(typeof data!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+=*$/.test(data)||data.length>6000000)fail(400,'写真を選び直してください');const type=data.slice(5,data.indexOf(';')),bytes=Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0));if(!bytes.length)fail(400,'写真が空です');const key=gid+'/'+crypto.randomUUID();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:type}});return key}
async function records(env,id){return (await env.DB.prepare('SELECT * FROM records WHERE group_id = ? ORDER BY created, id').bind(id).all()).results.map((r,i)=>({...JSON.parse(r.data),id:r.id,no:i+1,photo:r.photo,revision:r.revision}))}
export default {async fetch(req,env){const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);try{
 const user=identity(req),parts=url.pathname.split('/').filter(Boolean),method=req.method;
 if(method!=='GET'&&method!=='HEAD'){if(req.headers.get('origin')!==url.origin||!req.headers.get('content-type')?.startsWith('application/json'))fail(403,'この画面から操作をやり直してください');if(!user)fail(401,'ログインが必要です')}
 if(parts[1]==='session')return json({user,available:!!env.DB&&!!env.BUCKET});
 if(!env.DB||!env.BUCKET)fail(503,'共有保存を準備しています。個人の図鑑は引き続き使えます。');
 if(parts[1]==='public'){
  if(parts.length===2){const rows=(await env.DB.prepare('SELECT id, data, updated FROM publications ORDER BY updated DESC LIMIT 60').all()).results;return json({books:rows.map(r=>({id:r.id,book:JSON.parse(r.data).book,count:JSON.parse(r.data).entries.length,updated:r.updated}))})}
  const pub=await env.DB.prepare('SELECT data FROM publications WHERE id = ?').bind(parts[2]).first();if(!pub)fail(404,'この図鑑は公開されていません');const data=JSON.parse(pub.data);
  if(parts[3]==='media'){const photo=parts.slice(4).join('/');if(!data.entries.some(e=>e.photo===photo))fail(404,'写真が見つかりません');const obj=await env.BUCKET.get(photo);if(!obj)fail(404,'写真が見つかりません');return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata.contentType,'Cache-Control':'private,no-store','X-Content-Type-Options':'nosniff'}})}return json(data)
 }
 if(parts[1]!=='groups')fail(404,'ページが見つかりません');if(!user)fail(401,'ログインが必要です');
 if(parts.length===2){
  if(method==='GET'){const rows=(await env.DB.prepare('SELECT DISTINCT g.* FROM groups g LEFT JOIN members m ON m.group_id = g.id WHERE g.owner = ? OR m.email = ? ORDER BY g.created DESC').bind(user.id,user.email).all()).results;return json({groups:rows.map(g=>({id:g.id,book:JSON.parse(g.data),owner:g.owner===user.id,revision:g.revision}))})}
  if(method==='POST'){const input=await body(req),id=crypto.randomUUID(),data=bookData(input.book||{});await env.DB.prepare('INSERT INTO groups (id,owner,data,revision,created) VALUES (?,?,?,1,?)').bind(id,user.id,JSON.stringify(data),Date.now()).run();return json({id},201)}fail(405,'未対応の操作です')
 }
 const id=parts[2],group=await access(env,id,user),own=group.owner===user.id;
 if(parts[3]==='media'&&method==='GET'){const key=parts.slice(4).join('/');if(!key.startsWith(id+'/'))fail(403,'写真にアクセスできません');const obj=await env.BUCKET.get(key);if(!obj)fail(404,'写真が見つかりません');return new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata.contentType,'Cache-Control':'private,no-store'}})}
 if(parts.length===3){
  if(method==='GET'){const members=own?(await env.DB.prepare('SELECT email FROM members WHERE group_id = ?').bind(id).all()).results:[];return json({id,book:JSON.parse(group.data),revision:group.revision,owner:own,members,entries:await records(env,id),published:!!await env.DB.prepare('SELECT id FROM publications WHERE id = ?').bind(id).first()})}
  if(method==='PUT'){const input=await body(req),data=bookData(input.book||{});const result=await env.DB.prepare('UPDATE groups SET data = ?, revision = revision + 1 WHERE id = ? AND revision = ?').bind(JSON.stringify(data),id,input.revision).run();if(!result.meta.changes)fail(409,'ほかの人が更新しました。再読込してから変更を反映してください。');return json({ok:true})}
 }
 if(parts[3]==='members'){
  if(!own)fail(403,'招待の管理は作成者だけができます');const input=await body(req),email=clean(input.email,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'メールアドレスを確認してください');if(method==='POST')await env.DB.prepare('INSERT OR IGNORE INTO members (group_id,email,role) VALUES (?, ?, ?)').bind(id,email,'editor').run();else if(method==='DELETE')await env.DB.prepare('DELETE FROM members WHERE group_id = ? AND email = ?').bind(id,email).run();else fail(405,'未対応の操作です');return json({ok:true})
 }
 if(parts[3]==='publish'){
  if(!own)fail(403,'公開できるのは作成者だけです');
  if(method==='DELETE'){await env.DB.prepare('DELETE FROM publications WHERE id = ?').bind(id).run();return json({ok:true})}
  if(method!=='POST')fail(405,'未対応の操作です');const entries=await records(env,id);if(!entries.length)fail(400,'記録を1件以上追加してください');const b=JSON.parse(group.data);const snapshot={id,book:b,entries:entries.map(({id,no,name,kanji,observed,imagined,photo})=>({id,no,name,kanji,observed,imagined,photo}))};await env.DB.prepare('INSERT INTO publications (id,owner,data,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data, updated=excluded.updated').bind(id,user.id,JSON.stringify(snapshot),Date.now()).run();return json({ok:true})
 }
 if(parts[3]==='entries'){
  if(method==='DELETE'&&parts[4]){const input=await body(req);const result=await env.DB.prepare('DELETE FROM records WHERE id = ? AND group_id = ? AND revision = ?').bind(parts[4],id,input.revision).run();if(!result.meta.changes)fail(409,'ほかの人が更新しました。再読込して確認してください。');return json({ok:true})}
  const input=await body(req),data=entryData(input);
  if(method==='POST'){const sourceId=clean(input.sourceId,300);const eid=sourceId?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id+'|'+sourceId)))).map(n=>n.toString(16).padStart(2,'0')).join(''):crypto.randomUUID();if(sourceId&&await env.DB.prepare('SELECT id FROM records WHERE id = ? AND group_id = ?').bind(eid,id).first())return json({id:eid,reused:true});const photo=await savePhoto(env,id,input.photoData);await env.DB.prepare('INSERT OR IGNORE INTO records (id,group_id,data,photo,revision,created,author) VALUES (?,?,?,?,1,?,?)').bind(eid,id,JSON.stringify(data),photo,Date.now(),user.id).run();return json({id:eid},201)}
  if(method==='PUT'&&parts[4]){const current=await env.DB.prepare('SELECT photo, revision FROM records WHERE id = ? AND group_id = ?').bind(parts[4],id).first();if(!current)fail(404,'記録が見つかりません');if(current.revision!==input.revision)fail(409,'ほかの人がこの記録を更新しました。入力内容をコピーし、再読込してから保存してください。');const photo=input.photoData?await savePhoto(env,id,input.photoData):current.photo;let result;try{result=await env.DB.prepare('UPDATE records SET data = ?, photo = ?, revision = revision + 1 WHERE id = ? AND group_id = ? AND revision = ?').bind(JSON.stringify(data),photo,parts[4],id,input.revision).run()}catch(error){if(photo!==current.photo)await env.BUCKET.delete(photo);throw error}if(!result.meta.changes){if(photo!==current.photo)await env.BUCKET.delete(photo);fail(409,'ほかの人がこの記録を更新しました。入力内容をコピーし、再読込してから保存してください。')}return json({ok:true})}
 }fail(405,'未対応の操作です')
 }catch(e){if(!e.status)console.error('zukan-api',e);return json({error:e.status?e.message:'共有保存に接続できませんでした。入力を残して、もう一度お試しください。'},e.status||503)}}};
